name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Build
      run: |
        npm ci
        ./build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build
        path: build
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: |
        npm ci
        echo "./node_modules/.bin" >> $GITHUB_PATH
    - name: Run Prettier
      run: prettier --check .
    - name: Run eslint
      run: eslint .
